### ISSUE TITLE
Build on RHEL8.5/Python3.6 fails (numpy array issue?)

### ISSUE THREAD

**Issue by ralphlange** [epics-base/p4p#160]
I'm building p4p as an EPICS module on a RHEL8.5 system with Python 3.6, numpy 1.14.3.

While a build of p4p 4.1.12 works fine, building 4.2.0 fails with:
```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE       -DPY_ARRAY_UNIQUE_SYMBOL=PVXS_PyArray_API -DPVXS_ENABLE_EXPERT_API  -D__PYX_EXTERN_C=extern   -D_X86_64_  -DUNIX  -Dlinux      -O3 -g   -Wall    -Wno-unused-result -Wsign-compare  -std=c++11  -mtune=generic      -m64 -std=c++11  -fPIC -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include    -I/opt/codac-7.3/epics/include/compiler/gcc -I/opt/codac-7.3/epics/include/os/Linux -I/opt/codac-7.3/epics/include       -I/opt/codac-7.3/include   -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c _p4p.cpp
[WARN] _p4p.cpp: In function ‘int __pyx_pf_5numpy_7ndarray___getbuffer__(PyArrayObject*, Py_buffer*, int)’:
[ERROR] _p4p.cpp:18875:50: error: ‘NPY_C_CONTIGUOUS’ was not declared in this scope
[WARN] __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_C_CONTIGUOUS) != 0)) != 0);
[WARN] ^~~~~~~~~~~~~~~~
[WARN] _p4p.cpp:18875:50: note: suggested alternative: ‘PyBUF_C_CONTIGUOUS’
[WARN] __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_C_CONTIGUOUS) != 0)) != 0);
[WARN] ^~~~~~~~~~~~~~~~
[WARN] PyBUF_C_CONTIGUOUS
[ERROR] _p4p.cpp:18931:50: error: ‘NPY_F_CONTIGUOUS’ was not declared in this scope
[WARN] __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_F_CONTIGUOUS) != 0)) != 0);
[WARN] ^~~~~~~~~~~~~~~~
[WARN] _p4p.cpp:18931:50: note: suggested alternative: ‘PyBUF_F_CONTIGUOUS’
[WARN] __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_F_CONTIGUOUS) != 0)) != 0);
[WARN] ^~~~~~~~~~~~~~~~
[WARN] PyBUF_F_CONTIGUOUS
[ERROR] _p4p.cpp:19117:42: error: ‘PyArrayObject’ {aka ‘struct tagPyArrayObject’} has no member named ‘descr’
[WARN] __pyx_t_3 = ((PyObject *)__pyx_v_self->descr);
[WARN] ^~~~~
[WARN] In file included from /usr/include/python3.6m/pytime.h:6,
[WARN] from /usr/include/python3.6m/Python.h:77,
[WARN] from _p4p.cpp:4:
[WARN] _p4p.cpp: In function ‘void __pyx_f_5numpy_set_array_base(PyArrayObject*, PyObject*)’:
[ERROR] _p4p.cpp:20761:27: error: ‘PyArrayObject’ {aka ‘struct tagPyArrayObject’} has no member named ‘base’; did you mean ‘ob_base’?
[WARN] Py_XDECREF(__pyx_v_arr->base);
[WARN] ^~~~
[WARN] /usr/include/python3.6m/object.h:851:50: note: in definition of macro ‘Py_XDECREF’
[WARN] PyObject *_py_xdecref_tmp = (PyObject *)(op); \
[WARN] ^~
[ERROR] _p4p.cpp:20770:16: error: ‘PyArrayObject’ {aka ‘struct tagPyArrayObject’} has no member named ‘base’; did you mean ‘ob_base’?
[WARN] __pyx_v_arr->base = __pyx_v_baseptr;
[WARN] ^~~~
[WARN] ob_base
[WARN] _p4p.cpp: In function ‘PyObject* __pyx_f_5numpy_get_array_base(PyArrayObject*)’:
[ERROR] _p4p.cpp:20805:30: error: ‘PyArrayObject’ {aka ‘struct tagPyArrayObject’} has no member named ‘base’; did you mean ‘ob_base’?
[WARN] __pyx_t_1 = ((__pyx_v_arr->base == NULL) != 0);
[WARN] ^~~~
[WARN] ob_base
[WARN] In file included from /usr/include/python3.6m/pytime.h:6,
[WARN] from /usr/include/python3.6m/Python.h:77,
[WARN] from _p4p.cpp:4:
[ERROR] _p4p.cpp:20837:44: error: ‘PyArrayObject’ {aka ‘struct tagPyArrayObject’} has no member named ‘base’; did you mean ‘ob_base’?
[WARN] __Pyx_INCREF(((PyObject *)__pyx_v_arr->base));
[WARN] ^~~~
[WARN] /usr/include/python3.6m/object.h:786:19: note: in definition of macro ‘Py_INCREF’
[WARN] ((PyObject *)(op))->ob_refcnt++)
[WARN] ^~
[WARN] _p4p.cpp:20837:5: note: in expansion of macro ‘__Pyx_INCREF’
[WARN] __Pyx_INCREF(((PyObject *)__pyx_v_arr->base));
[WARN] ^~~~~~~~~~~~
[ERROR] _p4p.cpp:20838:41: error: ‘PyArrayObject’ {aka ‘struct tagPyArrayObject’} has no member named ‘base’; did you mean ‘ob_base’?
[WARN] __pyx_r = ((PyObject *)__pyx_v_arr->base);
[WARN] ^~~~
[WARN] ob_base
[WARN] make[2]: *** [/opt/codac-7.3/epics/configure/RULES_BUILD:267: _p4p.o] Error 1
[WARN] make[2]: *** Waiting for unfinished jobs....
[WARN] make[1]: *** [/opt/codac-7.3/epics/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
[WARN] make: *** [/opt/codac-7.3/epics/configure/RULES_DIRS:85: src.install] Error 2
make[2]: Leaving directory '.../p4p-4.2.0/src/O.linux-x86_64'
```

Looking at the commits, I assume some version requirement not being met, but I'm not sure which one.

**Comment by ralphlange** [comment]
```
python3-numpy.x86_64                       1:1.14.3-10.el8
python3-Cython.x86_64                      0.28.1-3.el8
python36.x86_64                            3.6.8-38.module+el8.5.0+12207+5c5719bc
```
all from regular RHEL respositories.

**Comment by ralphlange** [comment]
Not quite, actually. Cython is taken from AlmaLinux.

Here's a container recipe that shows the issue:
```
# Container: centos:8

# change dnf config .repo files to use vault.centos.org

dnf groupinstall "Development Tools"

dnf install -y epel-release

curl -L -O https://repo.almalinux.org/almalinux/8/PowerTools/x86_64/os/Packages/python3-Cython-0.28.1-3.el8.x86_64.rpm

dnf -y install readline-devel ncurses-devel glibc-devel perl perl-devel perl-Test-Simple perl-Test-Harness libevent-devel libxml2-devel python3-devel python3-numpy python3-nose2 ./python3-Cython-0.28.1-3.el8.x86_64.rpm

curl -L https://github.com/epics-base/epics-base/releases/download/R7.0.8.1/base-7.0.8.1.tar.gz | tar xzf -
curl -L https://github.com/epics-base/pvxs/archive/refs/tags/1.3.1.tar.gz | tar xzf -
curl -L https://github.com/epics-base/p4p/archive/refs/tags/4.2.0.tar.gz | tar xzf -

cat >> base-7.0.8.1/configure/os/CONFIG_SITE.Common.linuxCommon <<EOF
OP_SYS_CXXFLAGS += -std=c++11
EOF

cat >> p4p-4.2.0/configure/CONFIG_SITE <<EOF
PYTHON = python3
EOF

cat > RELEASE.local <<EOF
PVXS = /pvxs-1.3.1
P4P = /p4p-4.2.0
EPICS_BASE = /base-7.0.8.1
EOF

make -j4 -C base-7.0.8.1
make -C base-7.0.8.1 clean
make -j4 -C pvxs-1.3.1
make -C pvxs-1.3.1 clean

make -j4 -C p4p-4.2.0
```

**Comment by ralphlange** [comment]
Using `pip-3`-installed Cython gets me `Cython-3.0.11-py2.py3-none-any.whl`, which works fine for compiling p4p.

As - in the CODAC context - p4p is currently the only user of Cython on Python 3.6, I will switch from the AlmaLinux RPM to installing the working Cython from its wheel file.

All good.

**Comment by ralphlange** [comment]
Thanks for the good hint!

**Comment by ralphlange** [comment]
Actually...
As it turns out, we do have a science package that uses the same version of Cython, but for Python 3.11.

Now my Cython install creates `/usr/bin/Cython` pointing to my Python 3.6 version, which obviously doesn't go well with a parallel Cython install using Python 3.11.
Do you know how to handle such a conflict?

**Comment by mdavidsaver** [comment]
> Now my Cython install creates `/usr/bin/cython` ...

I suspect you will prove me wrong, but I didn't think this entry point was used by either P4P build method.  eg. the Makefile build calls:

https://github.com/epics-base/p4p/blob/9040d4bb56d58b674de1475dbb62444a056f6729/src/Makefile#L106

> Do you know how to handle such a conflict?

virtualenv?

**Comment by ralphlange** [comment]
Resolved.

Your build method doesn't use it, but the build method that our science group uses for some of their packages does. They hard-code the `cython` name for the binary without caring about anything else.
They're on RedHat 9 and use Python 3.11 as default Python, so they don't see the problem. We just want to re-package their stuff for our RedHat 8 based machines, without patching things every time.

We'll try talking them into using `$(PYTHON) -m cython ...` or something equivalent instead.
